---
deployment:
  tasks:
    - echo "➡️ Bắt đầu sao chép mã nguồn..."
    - rsync -a --exclude='.git' ./ /home/academix/api-academix.site/
    - echo "✅ Sao chép mã nguồn xong."

    - cd /home/academix/api-academix.site/

    - if [ -f package.json ]; then
        echo "📦 Cài đặt Node modules...";
        npm install --omit=dev;
        echo "🔧 Build ứng dụng...";
        npm run build;
      fi

    - echo "🚀 Hoàn tất triển khai."
